name: "Microsoft Teams Action"
description: "Send notifications to Microsoft Teams"
author: "Satya Tulasi Jalandhar C H"

inputs:
  GITHUB_TOKEN:
    type: string
    description: "GitHub token used for API authentication. Use secrets.GITHUB_TOKEN"
    required: true
  WEBHOOK_URI:
    type: string
    description: "Microsoft Teams Webhook URL"
    required: true
  DEBUG:
    type: boolean
    description: "Debug mode"
    required: false

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
  post-if: "always()"
