name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URI: ${{ secrets.WEBHOOK_URI }}
          DEBUG: true

      - name: Test Online Action
        uses: satyatulasijalandharch/Action-Testing@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URI: ${{ secrets.WEBHOOK_URI }}
          DEBUG: true